### Get Pods
GET http://localhost:8081/pods

### Create Pod
POST http://localhost:8081/pods

{
    "ID": "1",
    "Name": "my-pod2",
    "Image": "zalerix/webapp",
    "CPURequest": 100,
    "MemoryRequest": 50
}

### Delete pod
DELETE http://localhost:8081/pods/57ddf1eb8d2fec068d7371b31cd8a32cde7da3876e326ccfbf8bbb9c09f0fb6c