
### Metrics
GET http://localhost:8081/metrics

### Get Pods
GET http://localhost:8081/pods

### Create Pod
POST http://localhost:8081/pods

{
    "ID": "1",
    "Name": "my-pod",
    "Image": "zalerix/webapp",
    "CPURequest": 100,
    "MemoryRequest": 50
}

### Delete pod
DELETE http://localhost:8081/pods/57ddf1eb8d2fec068d7371b31cd8a32cde7da3876e326ccfbf8bbb9c09f0fb6c

### Pods Metrics
GET http://localhost:8081/pods/metrics

### POD Inspect
GET http://localhost:8081/pods/fae35e988a2d5a9a1445eeada66c341932b30bd243821ee14f8e9cb1fa2ab748